name: Branch Deploy
on:
  push:
    branch:
      - 'master'
    paths-ignore: # 下列文件的变更不触发部署
      - .editorconfig
      - .eslintrc
      - .gitignore
      - .prettierrc
      - README.md
      - LICENSE

jobs: # 工作流
  branch-deploy: # 工作流名称
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化
    steps: # 步骤
      # 下载源码
      - name: Checkout
        uses: actions/checkout@master

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
      - run: npm install
      - run: npm run build
      #- run: tar -zcvf release.tgz .nuxt static utils config.js nuxt.config.js package.json package-lock.json pm2.config.json
      - run: ls -a

      # 使用 sebastianpopp/ftp-action@releases/v2 插件，把 release.tgz 推送到远程服务器
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: caixusheng.com
          FTP_USERNAME: ${{ secrets.USERNAME }}
          FTP_PASSWORD: ${{ secrets.PASSWORD }}
          LOCAL_DIR: .nuxt static utils config.js nuxt.config.js package.json package-lock.json pm2.config.json
          REMOTE_DIR: /webapp/test
          ARGS: --delete
