name: Branch Deploy
on:
  push:
    branch:
      - 'master'
    paths-ignore: # 下列文件的变更不触发部署
      - .editorconfig
      - .eslintrc
      - .gitignore
      - .prettierrc
      - README.md
      - LICENSE

jobs:
  master-branch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - run: node -v
      - run: npm -v
      - run: node -v

