name: Branch Deploy
on:
  push:
    branch:
      - 'master'
    paths-ignore: # 下列文件的变更不触发部署
      - .editorconfig
      - .eslintrc
      - .gitignore  
      - .prettierrc
      - README.md
      - LICENSE

jobs: # 工作流
  branch-deploy: # 工作流名称
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化
    steps:
        - name: Checkout
          uses: actions/checkout@master
        
        - name: Install
          run: npm install

        - name: Build
          run: npm run build
        
        - name: Release
          run: tar -zcvf release.tgz .nuxt static utils config.js nuxt.config.js package.json package-lock.json pm2.config.json

        - name: ls -a
          run: ls -a
        
        # 为了将资源部署到云服务器，此处下载一个ssh传资料的工具
        - name: Setup sshpass
          run: sudo apt-get install sshpass

        # 部署
        - name: Deploy
          uses: garygrossgarten/github-action-scp@release
          with:
            local: release.tgz
            remote: /webapp/test
            # 涉及偏安全隐私的信息，不要明文暴露在此文件中，因为repo很可能是公开的，会被所有人看见
            # ${{ ... }} 会应用你在对应项目设置中，配置的对应serets的键值信息，从而保护私密信息不被看到
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }} 
            password: ${{ secrets.PASSWORD }}