name: Branch Deploy
on:
  push:
    branch:
      - 'master'
    paths-ignore: # 下列文件的变更不触发部署
      - .editorconfig
      - .eslintrc
      - .gitignore
      - .prettierrc
      - README.md
      - LICENSE

jobs:
  master-branch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: yarn install

      - name: Build
        run: npm run build

      - name: Release
        run: tar -zcvf release.tgz .nuxt static utils config.js nuxt.config.js package.json yarn.lock pm2.config.json

      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'release.tgz'
          target: '/webapp/diary'

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /webapp/diary
            tar zxvf release.tgz
            yarn install --production
            pm2 reload pm2.config.json
